### PR TITLE
.travis.yml: test with nix-build

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Unsure if it would be better to pin to a specific commit of `nixos-18.09`.

**Comment by Gabriel439** [comment]
@vaibhavsagar: This is fine for now.  As far as I'm concerned, you can make yourself as comfortable as you want with this repository 🙂 

I added you as a collaborator, too

However, you might be interested in using this for pinning purposes:

https://nixos.wiki/wiki/How_to_fetch_Nixpkgs_with_an_empty_NIX_PATH

**Comment by vaibhavsagar** [comment]
I thought this had been superseded by `builtins.fetchTarball` in Nix >= 2.0, is that not the case?

**Comment by Gabriel439** [comment]
> I thought this had been superseded by `builtins.fetchTarball` in Nix >= 2.0, is that not the case?

Yes, that is correct.  That page mentions the `builtins.fetchTarball`-only solution further down the page for the case where you don't need to support Nix 1.*

Also, feel free to merge this whenever you are ready

**Pull request merged**
